// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package projeto_estatico.domain;

import org.springframework.beans.factory.annotation.Configurable;
import projeto_estatico.domain.Jogador;

privileged aspect Jogador_Roo_Configurable {
    
    declare @type: Jogador: @Configurable;
    
}
