// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package projeto_estatico.domain;

import java.util.Set;
import projeto_estatico.domain.Jogador;

privileged aspect Jogador_Roo_JavaBean {
    
    public Set<Jogador> Jogador.getNome() {
        return this.nome;
    }
    
    public void Jogador.setNome(Set<Jogador> nome) {
        this.nome = nome;
    }
    
}
