// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package projeto_estatico.domain;

import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import projeto_estatico.domain.Jogador;
import projeto_estatico.domain.JogadorDataOnDemand;
import projeto_estatico.domain.JogadorIntegrationTest;

privileged aspect JogadorIntegrationTest_Roo_IntegrationTest {
    
    declare @type: JogadorIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: JogadorIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: JogadorIntegrationTest: @Transactional;
    
    @Autowired
    JogadorDataOnDemand JogadorIntegrationTest.dod;
    
    @Test
    public void JogadorIntegrationTest.testCountJogadors() {
        Assert.assertNotNull("Data on demand for 'Jogador' failed to initialize correctly", dod.getRandomJogador());
        long count = Jogador.countJogadors();
        Assert.assertTrue("Counter for 'Jogador' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void JogadorIntegrationTest.testFindJogador() {
        Jogador obj = dod.getRandomJogador();
        Assert.assertNotNull("Data on demand for 'Jogador' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Jogador' failed to provide an identifier", id);
        obj = Jogador.findJogador(id);
        Assert.assertNotNull("Find method for 'Jogador' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Jogador' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void JogadorIntegrationTest.testFindAllJogadors() {
        Assert.assertNotNull("Data on demand for 'Jogador' failed to initialize correctly", dod.getRandomJogador());
        long count = Jogador.countJogadors();
        Assert.assertTrue("Too expensive to perform a find all test for 'Jogador', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Jogador> result = Jogador.findAllJogadors();
        Assert.assertNotNull("Find all method for 'Jogador' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Jogador' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void JogadorIntegrationTest.testFindJogadorEntries() {
        Assert.assertNotNull("Data on demand for 'Jogador' failed to initialize correctly", dod.getRandomJogador());
        long count = Jogador.countJogadors();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Jogador> result = Jogador.findJogadorEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Jogador' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Jogador' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void JogadorIntegrationTest.testFlush() {
        Jogador obj = dod.getRandomJogador();
        Assert.assertNotNull("Data on demand for 'Jogador' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Jogador' failed to provide an identifier", id);
        obj = Jogador.findJogador(id);
        Assert.assertNotNull("Find method for 'Jogador' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyJogador(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Jogador' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void JogadorIntegrationTest.testMergeUpdate() {
        Jogador obj = dod.getRandomJogador();
        Assert.assertNotNull("Data on demand for 'Jogador' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Jogador' failed to provide an identifier", id);
        obj = Jogador.findJogador(id);
        boolean modified =  dod.modifyJogador(obj);
        Integer currentVersion = obj.getVersion();
        Jogador merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Jogador' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void JogadorIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Jogador' failed to initialize correctly", dod.getRandomJogador());
        Jogador obj = dod.getNewTransientJogador(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Jogador' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Jogador' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Jogador' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void JogadorIntegrationTest.testRemove() {
        Jogador obj = dod.getRandomJogador();
        Assert.assertNotNull("Data on demand for 'Jogador' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Jogador' failed to provide an identifier", id);
        obj = Jogador.findJogador(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Jogador' with identifier '" + id + "'", Jogador.findJogador(id));
    }
    
}
