// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package projeto_estatico.domain;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;
import projeto_estatico.domain.Liga;
import projeto_estatico.domain.LigaDataOnDemand;

privileged aspect LigaDataOnDemand_Roo_DataOnDemand {
    
    declare @type: LigaDataOnDemand: @Component;
    
    private Random LigaDataOnDemand.rnd = new SecureRandom();
    
    private List<Liga> LigaDataOnDemand.data;
    
    public Liga LigaDataOnDemand.getNewTransientLiga(int index) {
        Liga obj = new Liga();
        return obj;
    }
    
    public Liga LigaDataOnDemand.getSpecificLiga(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Liga obj = data.get(index);
        Long id = obj.getId();
        return Liga.findLiga(id);
    }
    
    public Liga LigaDataOnDemand.getRandomLiga() {
        init();
        Liga obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Liga.findLiga(id);
    }
    
    public boolean LigaDataOnDemand.modifyLiga(Liga obj) {
        return false;
    }
    
    public void LigaDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Liga.findLigaEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Liga' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Liga>();
        for (int i = 0; i < 10; i++) {
            Liga obj = getNewTransientLiga(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
