// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package projeto_estatico.domain;

import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import projeto_estatico.domain.Liga;
import projeto_estatico.domain.LigaDataOnDemand;
import projeto_estatico.domain.LigaIntegrationTest;

privileged aspect LigaIntegrationTest_Roo_IntegrationTest {
    
    declare @type: LigaIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: LigaIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: LigaIntegrationTest: @Transactional;
    
    @Autowired
    LigaDataOnDemand LigaIntegrationTest.dod;
    
    @Test
    public void LigaIntegrationTest.testCountLigas() {
        Assert.assertNotNull("Data on demand for 'Liga' failed to initialize correctly", dod.getRandomLiga());
        long count = Liga.countLigas();
        Assert.assertTrue("Counter for 'Liga' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void LigaIntegrationTest.testFindLiga() {
        Liga obj = dod.getRandomLiga();
        Assert.assertNotNull("Data on demand for 'Liga' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Liga' failed to provide an identifier", id);
        obj = Liga.findLiga(id);
        Assert.assertNotNull("Find method for 'Liga' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Liga' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void LigaIntegrationTest.testFindAllLigas() {
        Assert.assertNotNull("Data on demand for 'Liga' failed to initialize correctly", dod.getRandomLiga());
        long count = Liga.countLigas();
        Assert.assertTrue("Too expensive to perform a find all test for 'Liga', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Liga> result = Liga.findAllLigas();
        Assert.assertNotNull("Find all method for 'Liga' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Liga' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void LigaIntegrationTest.testFindLigaEntries() {
        Assert.assertNotNull("Data on demand for 'Liga' failed to initialize correctly", dod.getRandomLiga());
        long count = Liga.countLigas();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Liga> result = Liga.findLigaEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Liga' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Liga' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void LigaIntegrationTest.testFlush() {
        Liga obj = dod.getRandomLiga();
        Assert.assertNotNull("Data on demand for 'Liga' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Liga' failed to provide an identifier", id);
        obj = Liga.findLiga(id);
        Assert.assertNotNull("Find method for 'Liga' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyLiga(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Liga' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void LigaIntegrationTest.testMergeUpdate() {
        Liga obj = dod.getRandomLiga();
        Assert.assertNotNull("Data on demand for 'Liga' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Liga' failed to provide an identifier", id);
        obj = Liga.findLiga(id);
        boolean modified =  dod.modifyLiga(obj);
        Integer currentVersion = obj.getVersion();
        Liga merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Liga' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void LigaIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Liga' failed to initialize correctly", dod.getRandomLiga());
        Liga obj = dod.getNewTransientLiga(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Liga' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Liga' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Liga' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void LigaIntegrationTest.testRemove() {
        Liga obj = dod.getRandomLiga();
        Assert.assertNotNull("Data on demand for 'Liga' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Liga' failed to provide an identifier", id);
        obj = Liga.findLiga(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Liga' with identifier '" + id + "'", Liga.findLiga(id));
    }
    
}
